package org.usfirst.frc4904.robot;

import org.usfirst.frc4904.robot.subsystems.Lifter;

public class RobotMap {
	public static class Port {
		public static class HumanInput {
			public static final int joystick = 0;
			public static final int xboxController = 1;
		}

		public static class CANMotor {
			public static int liftMover = 0;
		}

		public static class PWM {}

		public static class CAN {}

		public static class Pneumatics {}
	}

	public static class Metrics {}

	public static class Component {
		public static Lifter lifter;
	}
	/**
	 * The static initializer runs exactly once and ensures that
	 * the variables are properly initialized.
	 */
	static {}

	/**
	 * Private constructor overrides the default package-public constructor auto-generated by Java
	 */
	private RobotMap() {
		//Lifter
		Motor liftMotor = new Motor ("Lift Motor", new CANTalon(Port.CANMotor.liftMover));
		Component.lifter = new Lifter(liftMotor);
	}
}
