package org.usfirst.frc4904.robot;

import org.usfirst.frc4904.robot.subsystems.Lifter;
import edu.wpi.first.wpilibj.DoubleSolenoid;

public class RobotMap {
	public static class Port {
		public static class HumanInput {
			public static final int joystick = 0;
			public static final int xboxController = 1;
		}

		public static class CANMotor {}

		public static class PWM {}

		public static class CAN {}

		public static class Pneumatics {
			public static int liftSupportOut = -1;
			public static int liftSupportIn = -1;
		}
	}

	public static class Metrics {}

	public static class Component {
		public static Lifter lifter;
		public static DoubleSolenoid liftPiston;
	}
	/**
	 * The static initializer runs exactly once and ensures that
	 * the variables are properly initialized.
	 */
	static {
		//Lifter
		Component.liftPiston = new DoubleSolenoid(Port.Pneumatics.liftSupportOut, Port.Pneumatics.liftSupportIn);
		Component.lifter = new Lifter(Component.liftPiston);
	}

	/**
	 * Private constructor overrides the default package-public constructor auto-generated by Java
	 */
	private RobotMap() {}
}
